version: '2'

services:
  corebot:
    image: outofcoffee/corebot
    build: ./bots/slack-deploy
    environment:
      SLACK_AUTH_TOKEN: "CHANGEME"
      SLACK_CHANNELS: "corebot"
      RUNDECK_API_TOKEN: "CHANGEME"
      RUNDECK_BASE_URL: "http://rundeck:4440"

  rundeck:
    image: jordan/rundeck
    container_name: rundeck
    environment:
      SERVER_URL: "http://localhost:4440"
    ports:
      - "4440:4440"
