# Default authz rules.
---
version: '1'

security:
  roles:
    # With great power, comes great responsibility.
    admin:
      permissions:
        - help
        - trigger
        - enable
        - disable
        - lock_action
        - unlock_action
        - status
        - lock_option
        - unlock_option
      tags:
        - all

  users:
    # Permits everyone to do everything.
    "*":
      roles:
        - admin
